// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svblqunxnvpkizrzsgwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2YmxxdW54bnZwa2l6cnpzZ3d1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQyODU5NDIsImV4cCI6MjA0OTg2MTk0Mn0.XpkYgqJkjjghIzHXx3nMPc3xVdCWxYtBJmkK5lE1J_w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);